### Documentación API (Scalar)
GET http://localhost:8080/docs

### Especificación OpenAPI JSON
GET http://localhost:8080/v3/api-docs

### Estado
GET http://localhost:8080/api/estado

### Rutas
GET http://localhost:8080/api/rutas

### Ruta 1
GET http://localhost:8080/api/rutas/1
